### ISSUE TITLE
Had an obstacle with peer dependencies.

### ISSUE THREAD

**Issue by adrianvalenz** [gregsullivan/_tw#1]
I ran 'npm install' initially to get the site set up, but there was some issues with peer dependencies needing to be installed. So prior to 'npm install' I installed some other packages. They are as follows:
"npm install eslint@latest postcss@latest prettier@latest stylelint@latest typescript@latest"...after which I ran 'npm install' and then 'npm run dev' and it created the style sheet I need in order to active the theme in my WordPress dashboard.

**Comment by gregsullivan** [comment]
Sorry for the very late response on this—I'm embarrassed to admit my GitHub notification settings were incorrect, and I only saw your issue today.

The peer dependencies you listed are all related to the `@wordpress/scripts` package, which was included to pull in configurations for `eslint` and `stylelint` since the WordPress configurations are referenced in `.eslintrc` and `.stylelintrc.json`. That said, they're not required for any of the scripts in `package.json`, so you can safely ignore the peer dependencies and build your CSS file as usual.

At present, the only peer dependency that gets flagged during `npm install` is `prettier`, and my thinking is that since there are different approaches to using Prettier, I leave it to the developer to decide which approach is best for them. If at some point I ended up adding scripts for CSS or JS linting, I would make sure that all required dependencies were installed.

To give an example of a use case that doesn't require installing Prettier: I use linting within my text editor, reading from the `.eslintrc` and `.stylelintrc.json` files to get the appropriate configurations, and I don't need to install anything else within the project aside from the configurations themselves.
