### ISSUE TITLE
How to disable purger

### ISSUE THREAD

**Issue by matheodino** [gregsullivan/_tw#11]
Hi, is _tw contains a default "purger"?

My styles seem to be purged, cause some custom color properties (like bg-primary) aren't printed if I don't use them (they are declared in theme.json). In fact, I use them with PHP which aren't recognized because of the order of the things, I guess. Can I disable this "purge" somewhere please? I don't see any in the builds, only a "safe list" in the Tailwind config.

Thanks!

**Comment by matheodino** [comment]
Sorry, I think just disabling safelist works.

**Comment by matheodino** [comment]
Oops no it doesn't.

**Comment by gregsullivan** [comment]
Hi @matheodino!

Tailwind CSS used to use PurgeCSS to remove unused classes. With version 3.0, it no longer does. I'd suggest reading this page for more details:

https://tailwindcss.com/docs/content-configuration

The general idea is that classes not found via your content configuration simply won't be included (as opposed to being included and then purged).

None of this is specific to _tw; the `safelist` key in `tailwind.config.js` simply prevents editor-specific styles from being purged (since they don't appear elsewhere in the theme's code). Otherwise, _tw's approach to classes is the standard approach used by Tailwind itself.
