### ISSUE TITLE
The folder structure makes this a no-go.

### ISSUE THREAD

**Issue by EmSixTeen** [gregsullivan/_tw#14]
Shouldn't need to be using symlinks just to set up a theme. I can do this, but it's an unnecessary complication both locally and on a server. Be smarter with .gitignore if there are assets/resources that shouldn't be committed to a repository. 

Just my two cents. Was looking forward to giving this a go, had it bookmarked for a while.

**Comment by gregsullivan** [comment]
Thanks for your feedback! I'm going to close this issue since I added a task for documenting non-symlink options for development to the project roadmap last week. (See [here](https://github.com/gregsullivan/_tw/commit/ca259b0ada240e0b9f9983ff4df4fa80343fe011).)

You're not meant to create a symlink in production, as only the `theme` folder should be deployed. The `bundle` command creates a zip file with only that folder that can be used for deployment as well. Please see the deployment documentation for details.

I'm not sure I understand how .gitignore could help, as those assets and resources are very much meant to be committed to a repository, but aren't meant to be deployed to production.

**Comment by gregsullivan** [comment]
There are no corresponding changes to the repository itself, but I've updated the documentation to cover setup in a local development environment without symlinking. I've also expanded the documentation for deployment to reenforce that only the `theme` folder should be deployed.

**Comment by EmSixTeen** [comment]
Thanks for the update! Will give it all another look when I get a bit of time. 🙂

**Comment by AdsonCicilioti** [comment]
Omg... I don't understand because you made this structure. Very bad on my opinion.

**Comment by gregsullivan** [comment]
@AdsonCicilioti Sorry to hear it doesn't work for you—I'd be happy to hear specifically what you don't understand, where you got hung up in the documentation, or why you think it's very bad.

**Comment by AdsonCicilioti** [comment]
> @AdsonCicilioti Sorry to hear it doesn't work for you—I'd be happy to hear specifically what you don't understand, or where you got hung up in the documentation.

I can't see the theme work with your assets. To see theme work i need generate theme.zip package and put it manually. I don't understand how i can develop the theme and see my modifications without proceed with manually theme generation.

**Comment by gregsullivan** [comment]
Do you have a local development environment? Have you followed the quick start instructions?

You should never need to generate a zip file except for deployment. (And many approaches to deployment would never use the zip file. It's just an option.)
