### ISSUE TITLE
postcss-simple-vars is not working

### ISSUE THREAD

**Issue by eliepartner** [gregsullivan/_tw#17]
Any node script doesn't work.

ERROR: "development:editor" exited with 1.

postcss-simple-vars is not working.
I tested it node v16.15.1

**Comment by gregsullivan** [comment]
Thanks for posting this!

The issue seems to have been triggered by [this commit from the Tailwind 3.1.5 release](https://github.com/tailwindlabs/tailwindcss/pull/8769) combined with my mistakenly leaving `postcss-import` precent in the `postcss.config.js` file after Tailwind 3.1 included that functionality itself.

The issue has been resolved here and in the generator. Please let me know if you encounter any other issues.
