### ISSUE TITLE
Theme installation failed.

### ISSUE THREAD

**Issue by manal80p** [gregsullivan/_tw#20]
Thanks for sharing this. I moved the folder that gets downloaded to the themes folder as mentioned in the README. However, the theme installation fails as there is no style.css in the this folder (its in the /theme folder). Is the content of the theme folder supposed to be moved to the main folder? Am I missing something here?

**Comment by gregsullivan** [comment]
Thanks for posting this!

Unfortunately, I can't duplicate this issue. Is there anything more you can tell me about your version of WordPress or anything else about your development environment that might be relevant?

What exactly are you seeing to indicate failure? ("However, the theme installation fails...")

I generated a fresh theme, copied it to a development server's `wp-content/theme` folder, and activated it without issue.

The only thing I can think of off the top of my head that would cause this issue is if you uploaded the .zip file from the generator directly to the "Upload Theme" box.

**Comment by manal80p** [comment]
Hi. Thanks for taking the time to respond.

Yes, I did upload the zip. That's the mistake. It works after I followed the docs.

Thanks again!

**Comment by gregsullivan** [comment]
No problem at all—thanks for the update!
