### ISSUE TITLE
Editor styles for Block Editor customisations

### ISSUE THREAD

**Issue by tareiking** [gregsullivan/_tw#25]
Hi @gregsullivan - do you have a current workflow for building custom blocks and having Tailwind compile the styles to view within the block editor screen?

I notice you had `Separate configuration files for front-end and editor builds` in your changelog, and I was curious about the approach you are using now?

I might be wrong, but it appears the editor-style.css is only designed to support tinymce, so would be super interested in your block customisation approach. For the time being, we generate a reduced `editor-style.css` and wrap any classes needed in the editor within the `.editor-styles-wrapper` selector.

Happy to share more, as our approach may be incorrect - but this allows us to use `enqueue_block_editor_assets` to enqueue our custom editor-style.css file.

**Comment by gregsullivan** [comment]
Hi @tareiking!

Workflows for custom blocks will vary pretty significantly depending on your project setup and the use case for the blocks.

I'll respond to some of your comments, then expand on approaches to custom blocks:

> I notice you had `Separate configuration files for front-end and editor builds` in your changelog, and I was curious about the approach you are using now?

This was prior to when I began using PostCSS to set an environment variable that allows for different options between the front-end and editor builds.

You can see the environment variable being set in `postcss.config.js` alongside the effect this has on the two selector variables. The environment variable is also used in `tailwind.config.js` to toggle Preflight off for the editor build.

> I might be wrong, but it appears the editor-style.css is only designed to support tinymce, so would be super interested in your block customisation approach. For the time being, we generate a reduced editor-style.css and wrap any classes needed in the editor within the .editor-styles-wrapper selector.

No, the `editor-style.css` file works within the block editor as well. Its primary goal is to support Tailwind Typography within the block editor, but it also adds the rest of your style sheet, so things like component classes are also passed on to the block editor.

Assuming your block's markup within the editor was the same on the front end and in the editor, having the appropriate classes in your _tw stylesheet should be enough to style it within the editor. If the goal is to use Tailwind classes, you'd just need to ensure your block markup is getting picked up by an entry in the `content` key in `tailwind.config.js`.

There are a number of ways you could do this, depending on your development setup and the location of your block repository or repositories. Here are some approaches I've used or other people have told me they've used, in no particular order:

* Put your block plugins inside the _tw repository (which may require symlinking or an otherwise creative approach to getting the theme and plugins working simultaneously within WordPress)
* In your custom block repository, add a filter to the dynamic block's HTML markup, and then use that filter to put the block's markup in your _tw repository
* Use a relative path in the `tailwind.config.js` `content` key, pointing outside your _tw repository (which ends up assuming you can have other developers working on the project use the exact same development set up as you, which may or may not be possible)
* Manually safelist the utility classes required by your block

I could likely think of some others, but hopefully that helps to give you some ideas of what is possible!

**Comment by tareiking** [comment]
@gregsullivan - I truly appreciate the time you take to explain things, props!

I actually didn't realise the relationship that `postcss.config.js` had in the build process, so I will experiment more with that approach as it seems to make sense.

### Storytime 📖 

You are right, `_tw` does work as expected for editor work - but what my initial problem (and subsequent rabbit hole) ended up being is the use of a Google Variable Font [Montserrat](https://fonts.google.com/specimen/Montserrat). Using the `@import` string of `@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;1,100&display=swap');` meant the font wasn't loading... and I thought this was a `_TW` specific issue... **it wasn't**.

Unbeknownst to me, variable fonts have nuanced browser and WP support.. and while I have yet to dive deeper into that - we ended up self-hosting the fonts and using `@font-face` within `custom/fonts.css` to work as expected.

Everything worked exactly as you said when I used a google font without both italic and normal variations (which I assume is super common).

**It is possible** to not self host, and maybe do two import statements one for italic, one for normal.. but is largely outside the scope of `_tw`.

@gregsullivan - again, really appreciate your work here! Time to keep building, I can confirm that styles are loaded as expected within the block editor content as you mention, so feel free to close this out 🍰 🎁

**Comment by gregsullivan** [comment]
@tareiking No problem at all—happy it helped!

I spent years carefully flattening OpenType features into separate web fonts, and I've applied that same backwards compatibility paranoia to variable fonts by not using them yet. Which is to say I hadn't run into that issue so far, but I'm glad you were able to resolve it, and I'll wait a bit longer to use variable fonts in production!

I'll close this out, but please don't hesitate to comment again if you have more questions or comments.
