### ISSUE TITLE
Tailwind css v3.0 Support

### ISSUE THREAD

**Issue by dojod** [gregsullivan/_tw#4]
Any plan to update this to tailwind v3.0?

**Comment by gregsullivan** [comment]
Yes, absolutely! Because the theme relies on Tailwind Typography, I was waiting for [today's release of 0.5.0](https://tailwindcss.com/blog/tailwindcss-typography-v0-5) and its accompanying documentation. With its release now official, I need to do some experimentation with the new `.prose-*` classes and figure out the best way to provide block editor support.

I can't commit to a timeframe for this due to the holidays, but work is underway. I'll update this issue as things progress.

**Comment by gregsullivan** [comment]
I'm expecting to complete these updates late this week or early next week. My next comment should coincide with closing this issue. Thanks for your patience!

**Comment by gregsullivan** [comment]
I've now updated the generator at [underscoretw.com](https://underscoretw.com/) and all of the corresponding documentation. The Tailwind Typography integration has changed significantly due to the major changes to Tailwind Typography itself.

I haven't updated this repository to reflect the changed output from the generator. I should be able to do that tomorrow; I just need to finish documenting all of the changes.

**Comment by gregsullivan** [comment]
All that's left now is to update the changelog. I'm going to consider this closed in the meantime!
