### ISSUE TITLE
Updating _tw

### ISSUE THREAD

**Issue by jackfaulkner** [gregsullivan/_tw#49]
Thanks for updating _tw to use the new features of Tailwind 3.2 recently. I'd like to upgrade an existing project accordingly. Is that possible/recommended? Is it as simple as updating the Tailwind package, or is there more to it?

**Comment by gregsullivan** [comment]
Thanks for posting this issue!

I'll be updating _tw with Tailwind 3.3 and a number of other changes late this week or some time next week. When I do, I'll try to include all changes related to the 3.3 upgrade in a single commit for reference.

In the meantime, I don't think you'll run into issues simply updating the package. The only other thing I know 100% that I'll be doing is removing the `line-clamp` plugin (since its functionality is now part of Tailwind itself).

I'll comment again when I've completed those updates!

**Comment by gregsullivan** [comment]
Here is the relevant commit:

https://github.com/gregsullivan/_tw/commit/90e12125851dccace1fc39b2d25cd65ce622c369

As expected, the only change specific to Tailwind 3.3 was the removal of `@tailwindcss/line-clamp`. (The commit above also updates all other npm dependencies.)

Please let me know if you have any questions or comments! I'm going to close this issue in the meantime.

**Comment by jackfaulkner** [comment]
Thanks @gregsullivan! I've updated a couple of sites to 3.3 now and it's been smooth sailing so far.

**Comment by gregsullivan** [comment]
Awesome, @jackfaulkner—very happy to hear it!
