### ISSUE TITLE
Tailwind CSS 3.4.0 update?

### ISSUE THREAD

**Issue by screenfluent** [gregsullivan/_tw#90]
Hi Greg, I am complete newbie in terms of working with code, so I don't know if it does any difference or not, however I'm curious if do you plan to update your theme to most recent Tailwind CSS version?

**Comment by gregsullivan** [comment]
Hi Szymon—Thanks for posting your question!

I do plan to update the _tw generator with Tailwind 3.4. I'm targeting the end of this week, so that the update has been made ahead of the holidays.

You may be able to update your own dependencies in the meantime; me completing the update is more of an assurance that I've tested that combination of dependencies and found that they work as expected.

Please let me know if you have any other questions in the meantime! I'll close this issue with another comment when the updates are complete.

**Comment by screenfluent** [comment]
Many thanks for your quick reply! I've been searching for months for the best way to launch my website with full control over the layout and still learn to code in the process. Your presentation on the WordPress YouTube channel was a turning point for me - it's the perfect starting point for my blog. Big thanks for that and for the _tw of course!

The reason I asked about updating to Tailwind 3.4 is that I'm not sure about updating the theme without breaking anything later on.

Also, I have one more question: Is there a Discord server or a Facebook group for your starter theme where I could ask about the best practices, especially for performance? Thank you again so much!

**Comment by gregsullivan** [comment]
No problem at all! I'm very happy you found the video helpful—I'd like to create an updated version since I recorded that one on almost no notice, and that someone found it useful definitely motivates me to get that done.

You'll be able to update afterward. The general philosophy of _tw is that you don't need to worry about keeping your generated theme in sync with the project. You can update npm packages as usual, and if a new version of WordPress causes any issues, I will document how to update previously generated themes to solve those issues. (This has only happened once.)

The best place to ask questions is on GitHub, in the [Discussions tab](https://github.com/gregsullivan/_tw/discussions). If I add more places to discuss _tw, I'll link to them from the _tw website!

**Comment by gregsullivan** [comment]
I've updated _tw with Tailwind CSS 3.4.0:

https://github.com/gregsullivan/_tw/commit/04f8fa68465c26ad2ed348c46bfe81dc6f8b1020

Please let me know if you run into any issues, or if you have any questions!
